# Name(s)
**Elliot Brainerd**

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

In [40]:
print("What are LaTeX equations referenced in the Notebook Documents section in the first link?\nWhat's the difference between Python and IPython?\nWhat is a modal user interface?")

What are LaTeX equations referenced in the Notebook Documents section in the first link?
What's the difference between Python and IPython?
What is a modal user interface?


In [42]:
## Exercises 1-7
print("For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.")

For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.


## Exercise 1

In [43]:
import numpy as np

arr1 = np.array([[2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2]])

print(arr1)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


## Exercise 2

In [44]:
arr2 = np.ones((6,4))
eye_arr = np.eye(6,4)
arr2 = arr2 + (2 * eye_arr)
print(arr2)

[[3. 1. 1. 1.]
 [1. 3. 1. 1.]
 [1. 1. 3. 1.]
 [1. 1. 1. 3.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Exercise 3

In [45]:
# YOUR SOLUTION HERE
print("The * multiplies the matrices element-wise while the other does the dot product.\nThe dot product does not work because the column size of arr1 does not equal row size of arr2.") 

The * multiplies the matrices element-wise while the other does the dot product.
The dot product does not work because the column size of arr1 does not equal row size of arr2.


## Exercise 4

In [46]:
# YOUR SOLUTION HERE
print(np.dot(arr1.transpose(), arr2))
print(np.dot(arr1, arr2.transpose()))

print("The dimensions of the arrays flip during a transposition, therefore the dot product will have different dimensions.")

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]]
The dimensions of the arrays flip during a transposition, therefore the dot product will have different dimensions.


## Exercise 5

In [47]:
# YOUR SOLUTION HERE
def my_func():
    print("hello")
my_func()

hello


## Exercise 6

In [48]:
# YOUR SOLUTION HERE
def arr_funcs():
    arr1 = np.random.rand(6,4)
    arr2 = np.random.rand(6,4)
    
    print(np.sum(arr1))
    print(np.sum(arr2))
    
    print(np.mean(arr1))
    print(np.mean(arr2))
    
    print(np.linalg.pinv(arr1))
    print(np.linalg.pinv(arr2))
    
arr_funcs()



11.971668287230496
12.832421406212436
0.49881951196793733
0.5346842252588515
[[-0.66408905  0.43815954  0.2836557  -0.06426135  0.60849434  0.10958531]
 [ 0.4081031  -1.16082847  0.31153279  0.0039493  -0.06979483  1.07360976]
 [ 1.56590765 -0.34031121  0.19853006 -1.6097786  -0.34860505  0.63742206]
 [-0.17236452  0.72623314 -0.4137403   1.10208666 -0.11807265 -0.73963642]]
[[ 0.14293829 -1.28447537  0.40458523  1.37442596 -1.19249253  0.04000261]
 [ 0.14672953  1.4940186  -0.53691639 -0.32282455  0.1052876  -0.03353751]
 [ 1.45276994 -0.51968782 -1.00603335 -0.38095338  1.04951405 -0.2883424 ]
 [-0.7103802   0.28618334  0.901863   -0.45303178  0.49388714  0.43948975]]


## Exercise 7

In [49]:
# YOUR SOLUTION HERE
def find_ones(arr):
    count = 0
    for i in arr:
        for j in i:
            if j == 1:
                count = count + 1
    return count

eye_arr = np.eye(6,4)
print(find_ones(eye_arr))
#print(np.where(a>2,0,1))

4


## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [50]:
# YOUR SOLUTION HERE
import pandas as pd
arr1 = np.array([[2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2]])
df = pd.DataFrame(arr1)
df

0  1  2  3
0  2  2  2  2
1  2  2  2  2
2  2  2  2  2
3  2  2  2  2
4  2  2  2  2
5  2  2  2  2

## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [51]:
# YOUR SOLUTION HERE
arr2 = np.ones((6,4))
df = pd.DataFrame(arr2)

for i in range(6):
    for j in range(4):
        if i == j:
            df[i][j] += 2
df

0    1    2    3
0  3.0  1.0  1.0  1.0
1  1.0  3.0  1.0  1.0
2  1.0  1.0  3.0  1.0
3  1.0  1.0  1.0  3.0
4  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [52]:
# YOUR SOLUTION HERE
print(arr1 * arr2)
print("This is element-wise multiplication (*)")
print("We can't use the dot product because the dimensions of arr1 and arr2 are not aligned properly")


[[6. 2. 2. 2.]
 [2. 6. 2. 2.]
 [2. 2. 6. 2.]
 [2. 2. 2. 6.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
This is element-wise multiplication (*)
We can't use the dot product because the dimensions of arr1 and arr2 are not aligned properly


## Exercise 11
Repeat exercise A.7 using a dataframe.

In [69]:
# YOUR SOLUTION HERE
arr2 = np.eye(6,4)
df = pd.DataFrame(arr2)

count1 = 0
count2 = 0

for i in range(6):
    for j in range(4):
        if df.iloc[i, j] == 1:
            count1 += 1

for i in range(4):
    count2 += (df[i] == 1).sum()
            
print(count1)
print(count2)

4
4


## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [32]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [33]:
## YOUR SOLUTION HERE

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [34]:
## YOUR SOLUTION HERE
titanic_df.set_index('sex',inplace=True)

## Exercise 14
How do you reset the index?

In [35]:
## YOUR SOLUTION HERE